{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"191002_CNNipynb","provenance":[],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"code","metadata":{"id":"HT-EL64V--mU","colab_type":"code","outputId":"07264f89-f151-4c0f-bb9e-415406917871","executionInfo":{"status":"ok","timestamp":1569994902802,"user_tz":-540,"elapsed":1003,"user":{"displayName":"양한솔","photoUrl":"","userId":"12251541929954576282"}},"colab":{"base_uri":"https://localhost:8080/","height":89}},"source":["import tensorflow as tf\n","from tensorflow.examples.tutorials.mnist import input_data\n","mnist = input_data.read_data_sets(\"./mnist/data/\", one_hot=True)"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Extracting ./mnist/data/train-images-idx3-ubyte.gz\n","Extracting ./mnist/data/train-labels-idx1-ubyte.gz\n","Extracting ./mnist/data/t10k-images-idx3-ubyte.gz\n","Extracting ./mnist/data/t10k-labels-idx1-ubyte.gz\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"0Q37dGP4_Hde","colab_type":"code","colab":{}},"source":["X = tf.placeholder(tf.float32, [None, 28, 28, 1])\n","Y = tf.placeholder(tf.float32, [None, 10])\n","is_training = tf.placeholder(tf.bool)"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"V28kJ79Z_MAL","colab_type":"code","outputId":"8ae3c080-2764-4bf1-a8b1-6e99ee5fb489","executionInfo":{"status":"ok","timestamp":1569995390697,"user_tz":-540,"elapsed":1053,"user":{"displayName":"양한솔","photoUrl":"","userId":"12251541929954576282"}},"colab":{"base_uri":"https://localhost:8080/","height":505}},"source":["L1 = tf.layers.conv2d(X,32,[3,3])\n","L1 = tf.layers.max_pooling2d(L1, [2,2], [2,2])\n","L1 = tf.layers.dropout(L1, 0.7, is_training)\n","\n","L2 = tf.layers.conv2d(L1, 64, [3,3])\n","L2 = tf.layers.max_pooling2d(L2, [2,2], [2,2])\n","L2 = tf.layers.dropout(L2, 0.7, is_training)\n","\n","L3 = tf.contrib.layers.flatten(L2)\n","L3 = tf.layers.dense(L3, 256, activation=tf.nn.relu)\n","L3 = tf.layers.dropout(L3, 0.5, is_training)\n","\n","model = tf.layers.dense(L3, 10, activation=None)"],"execution_count":0,"outputs":[{"output_type":"stream","text":["WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d0f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Pooling2D.call of <tensorflow.python.layers.pooling.MaxPooling2D object at 0x7f9e31d9d0f0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use keras.layers.flatten instead.\n","WARNING:tensorflow:Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9e31e235c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9e31e235c0>>: AttributeError: module 'gast' has no attribute 'Num'\n","WARNING: Entity <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9e31e235c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Flatten.call of <tensorflow.python.layers.core.Flatten object at 0x7f9e31e235c0>>: AttributeError: module 'gast' has no attribute 'Num'\n","WARNING:tensorflow:From <ipython-input-6-68b2411a2af4>:10: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.\n","Instructions for updating:\n","Use keras.layers.dense instead.\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31d9d940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31d9d940>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d90e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d90e10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d90e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dropout.call of <tensorflow.python.layers.core.Dropout object at 0x7f9e31d90e10>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING:tensorflow:Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31e235c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31e235c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n","WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31e235c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x7f9e31e235c0>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"udVFpnYfAJ-t","colab_type":"code","colab":{}},"source":["cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=model, labels=Y))\n","optimizer = tf.train.AdamOptimizer(0.001).minimize(cost)"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"S0DA46pDBMUs","colab_type":"code","outputId":"75b4edb6-c227-4e73-de85-51301f9bebca","executionInfo":{"status":"ok","timestamp":1569996207729,"user_tz":-540,"elapsed":377089,"user":{"displayName":"양한솔","photoUrl":"","userId":"12251541929954576282"}},"colab":{"base_uri":"https://localhost:8080/","height":269}},"source":["%%time\n","#########\n","# 신경망 모델 학습\n","######\n","init = tf.global_variables_initializer()\n","sess = tf.Session()\n","sess.run(init)\n","\n","batch_size = 100\n","total_batch = int(mnist.train.num_examples / batch_size)\n","                  \n","for epoch in range(10):\n","  total_cost = 0\n","  for i in range(total_batch):\n","      batch_xs, batch_ys = mnist.train.next_batch(batch_size)\n","  # 이미지 데이터를 CNN 모델을 위한 자료형태인 [28 28 1] 의 형태로 재구성합니다.\n","      batch_xs = batch_xs.reshape(-1, 28, 28, 1)\n","      _, cost_val = sess.run([optimizer, cost],\n","                            feed_dict={X: batch_xs,\n","                                        Y: batch_ys,\n","                                        is_training: True})\n","\n","      total_cost += cost_val\n","                  \n","  print('Epoch:', '%04d' % (epoch + 1),\n","        'Avg. cost =', '{:.3f}'.format(total_cost / total_batch))\n","print('최적화 완료!')"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Epoch: 0001 Avg. cost = 0.175\n","Epoch: 0002 Avg. cost = 0.046\n","Epoch: 0003 Avg. cost = 0.030\n","Epoch: 0004 Avg. cost = 0.021\n","Epoch: 0005 Avg. cost = 0.017\n","Epoch: 0006 Avg. cost = 0.012\n","Epoch: 0007 Avg. cost = 0.009\n","Epoch: 0008 Avg. cost = 0.010\n","Epoch: 0009 Avg. cost = 0.008\n","Epoch: 0010 Avg. cost = 0.009\n","최적화 완료!\n","CPU times: user 12min 3s, sys: 8.69 s, total: 12min 12s\n","Wall time: 6min 16s\n","Parser   : 118 ms\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"q2_7RvznB7Rs","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]}]}